# Generated by Django 2.0.6 on 2018-07-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_auto_20180712_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
